/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operandi {
	int op1;
	int op2;
};
typedef struct Operandi Operandi;

#define OPERAZIONIPROG 0x20000013
#define OPERAZIONIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMMA 1
extern  int * somma_1(Operandi *, CLIENT *);
extern  int * somma_1_svc(Operandi *, struct svc_req *);
#define MOLTIPLICAZIONE 2
extern  int * moltiplicazione_1(Operandi *, CLIENT *);
extern  int * moltiplicazione_1_svc(Operandi *, struct svc_req *);
extern int operazioniprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMMA 1
extern  int * somma_1();
extern  int * somma_1_svc();
#define MOLTIPLICAZIONE 2
extern  int * moltiplicazione_1();
extern  int * moltiplicazione_1_svc();
extern int operazioniprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operandi (XDR *, Operandi*);

#else /* K&R C */
extern bool_t xdr_Operandi ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
