/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SALA_H_RPCGEN
#define _SALA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LUNGHFILA 7
#define NUMFILE 10

struct Input {
	char tipo;
	int fila;
	int colonna;
};
typedef struct Input Input;

struct Fila {
	char posto[LUNGHFILA];
};
typedef struct Fila Fila;

struct Sala {
	Fila fila[NUMFILE];
};
typedef struct Sala Sala;

#define SALA 0x20000013
#define SALAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRENOTA_POSTAZIONE 1
extern  int * prenota_postazione_1(Input *, CLIENT *);
extern  int * prenota_postazione_1_svc(Input *, struct svc_req *);
#define VISUALIZZA_STATO 2
extern  Sala * visualizza_stato_1(void *, CLIENT *);
extern  Sala * visualizza_stato_1_svc(void *, struct svc_req *);
extern int sala_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRENOTA_POSTAZIONE 1
extern  int * prenota_postazione_1();
extern  int * prenota_postazione_1_svc();
#define VISUALIZZA_STATO 2
extern  Sala * visualizza_stato_1();
extern  Sala * visualizza_stato_1_svc();
extern int sala_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Fila (XDR *, Fila*);
extern  bool_t xdr_Sala (XDR *, Sala*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Fila ();
extern bool_t xdr_Sala ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SALA_H_RPCGEN */
